import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../dispatch/models/delivery.dart';

class DeliveryPdfBuilder {
  static const _brandBlue = PdfColor.fromInt(0xFF1E3A8A);
  static const _ink = PdfColor.fromInt(0xFF111827);
  static const _muted = PdfColor.fromInt(0xFF6B7280);
  static const _rule = PdfColor.fromInt(0xFFD1D5DB);
  static const _ruleSoft = PdfColor.fromInt(0xFFE5E7EB);
  static const _bg = PdfColor.fromInt(0xFFF9FAFB);
  static const _successGreen = PdfColor.fromInt(0xFF059669);
  static const _dangerRed = PdfColor.fromInt(0xFFDC2626);

  static final _dtFmt = DateFormat('d MMM y · HH:mm');
  static final _timeFmt = DateFormat('HH:mm · d MMM y');

  static Future<List<int>> build({
    required Delivery delivery,
    required String orgName,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(28, 28, 28, 28),
        header: (c) => _pageHeader(orgName),
        footer: (c) => _pageFooter(c, orgName),
        build: (c) => [
          _metaBlock(delivery),
          pw.SizedBox(height: 14),
          _summaryStrip(delivery),
          pw.SizedBox(height: 14),
          _sectionTitle('Stop Details'),
          pw.SizedBox(height: 6),
          _stopsTable(delivery),
          pw.SizedBox(height: 24),
          _signatureLine(),
        ],
      ),
    );
    return doc.save();
  }

  static pw.Widget _pageHeader(String orgName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              orgName.toUpperCase(),
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
                color: _brandBlue,
                letterSpacing: 1.2,
              ),
            ),
            pw.Text(
              'DELIVERY REPORT',
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
                color: _muted,
                letterSpacing: 1.2,
              ),
            ),
          ],
        ),
        pw.Divider(color: _brandBlue, thickness: 1.5),
        pw.SizedBox(height: 4),
      ],
    );
  }

  static pw.Widget _pageFooter(pw.Context c, String orgName) {
    return pw.Column(
      children: [
        pw.Divider(color: _rule, thickness: 0.5),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Opstation · $orgName',
              style: pw.TextStyle(fontSize: 8, color: _muted),
            ),
            pw.Text(
              'Page ${c.pageNumber} of ${c.pagesCount}',
              style: pw.TextStyle(fontSize: 8, color: _muted),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _metaBlock(Delivery d) {
    final rows = [
      ['Driver', d.driverName ?? 'Unassigned'],
      ['Created by', '${d.createdByName} (${d.createdByRole})'],
      ['Created', _dtFmt.format(d.createdAt)],
      if (d.startedAt != null) ['Started', _dtFmt.format(d.startedAt!)],
      if (d.completedAt != null)
        [
          d.status == DeliveryStatus.cancelled ? 'Cancelled' : 'Completed',
          _dtFmt.format(d.completedAt!),
        ],
      ['Status', d.status.label],
      if (d.notes != null && d.notes!.isNotEmpty) ['Notes', d.notes!],
    ];

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _bg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        border: pw.Border.all(color: _ruleSoft, width: 0.5),
      ),
      child: pw.Column(
        children: rows
            .map(
              (r) => pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Row(
                  children: [
                    pw.SizedBox(
                      width: 90,
                      child: pw.Text(
                        r[0],
                        style: pw.TextStyle(
                          fontSize: 9,
                          color: _muted,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ),
                    pw.Expanded(
                      child: pw.Text(
                        r[1],
                        style: pw.TextStyle(fontSize: 9, color: _ink),
                      ),
                    ),
                  ],
                ),
              ),
            )
            .toList(),
      ),
    );
  }

  static pw.Widget _summaryStrip(Delivery d) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        color: PdfColor.fromInt(0xFFEFF6FF),
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 14),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _summaryCell('STOPS', '${d.stops.length}', _ink),
          _summaryCell('DELIVERED', '${d.deliveredCount}', _successGreen),
          _summaryCell('FAILED', '${d.failedCount}', _dangerRed),
          _summaryCell('SHOULD COLLECT', 'Rs ${d.cashAmount}', _brandBlue),
          _summaryCell('COLLECTED', 'Rs ${d.cashCollected}', _successGreen),
        ],
      ),
    );
  }

  static pw.Widget _summaryCell(String label, String value, PdfColor color) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(label, style: pw.TextStyle(fontSize: 7, color: _muted)),
      ],
    );
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          text.toUpperCase(),
          style: pw.TextStyle(
            fontSize: 8,
            fontWeight: pw.FontWeight.bold,
            color: _brandBlue,
            letterSpacing: 1.0,
          ),
        ),
        pw.Divider(color: _rule, thickness: 0.5),
      ],
    );
  }

  static pw.Widget _stopsTable(Delivery d) {
    pw.TextStyle headerBold() =>
        pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _muted);

    return pw.Table(
      columnWidths: {
        0: const pw.FixedColumnWidth(18),  // #
        1: const pw.FlexColumnWidth(3),    // Customer + timestamp
        2: const pw.FlexColumnWidth(3),    // Item
        3: const pw.FixedColumnWidth(52),  // Should collect
        4: const pw.FixedColumnWidth(46),  // Collected
        5: const pw.FixedColumnWidth(50),  // Outcome
        6: const pw.FixedColumnWidth(36),  // Photo
      },
      border: pw.TableBorder(
        horizontalInside: pw.BorderSide(color: _ruleSoft, width: 0.5),
      ),
      children: [
        // Header row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _bg),
          children: [
            _th('#', headerBold()),
            _th('Customer', headerBold()),
            _th('Item', headerBold()),
            _th('Should Collect', headerBold()),
            _th('Collected', headerBold()),
            _th('Outcome', headerBold()),
            _th('Photo', headerBold()),
          ],
        ),
        // Data rows
        for (final s in d.stops)
          pw.TableRow(
            decoration: pw.BoxDecoration(
              color: s.status == DeliveryStopStatus.delivered
                  ? const PdfColor.fromInt(0xFFF0FDF4)
                  : s.status == DeliveryStopStatus.failed
                      ? const PdfColor.fromInt(0xFFFEF2F2)
                      : null,
            ),
            children: [
              // #
              _td('${s.sequence + 1}',
                  pw.TextStyle(fontSize: 8)),

              // Customer name + code + timestamp
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(s.customerName,
                        style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold)),
                    pw.Text(s.customerCode,
                        style: pw.TextStyle(fontSize: 7, color: _muted)),
                    if (s.deliveredAt != null)
                      pw.Text(
                        _timeFmt.format(s.deliveredAt!),
                        style: pw.TextStyle(fontSize: 7, color: _muted),
                      ),
                  ],
                ),
              ),

              // Item
              _td(
                s.itemDescription.isEmpty ? '-' : s.itemDescription,
                pw.TextStyle(fontSize: 8, color: _muted),
              ),

              // Should collect
              _td(
                'Rs ${s.amount}\n${s.paymentType.label}',
                pw.TextStyle(fontSize: 8),
              ),

              // Collected (actual)
              _td(
                s.status == DeliveryStopStatus.delivered
                    ? 'Rs ${s.cashReceived ?? s.amount}'
                    : '-',
                pw.TextStyle(
                  fontSize: 8,
                  color: s.status == DeliveryStopStatus.delivered
                      ? _successGreen
                      : _muted,
                ),
              ),

              // Outcome
              _outcomeCell(s),

              // Photo validation
              _photoCell(s),
            ],
          ),
      ],
    );
  }

  static pw.Widget _th(String text, pw.TextStyle style) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      child: pw.Text(text, style: style),
    );
  }

  static pw.Widget _td(String text, pw.TextStyle style) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      child: pw.Text(text, style: style),
    );
  }

  static pw.Widget _outcomeCell(DeliveryStop s) {
    PdfColor color;
    String label;
    switch (s.status) {
      case DeliveryStopStatus.delivered:
        color = _successGreen;
        label = 'Delivered';
        break;
      case DeliveryStopStatus.failed:
        color = _dangerRed;
        label = 'Failed';
        if (s.failureReason != null && s.failureReason!.isNotEmpty) {
          label += '\n${s.failureReason}';
        }
        break;
      case DeliveryStopStatus.pending:
        color = _muted;
        label = 'Pending';
        break;
    }
    // Verification note
    String verif = '';
    if (s.verification == DeliveryStopVerification.outside &&
        s.distanceMeters != null) {
      final dist = s.distanceMeters!;
      verif = dist >= 1000
          ? '\n${(dist / 1000).toStringAsFixed(1)}km off'
          : '\n${dist}m off';
    } else if (s.verification == DeliveryStopVerification.noLocation) {
      verif = '\nNo GPS';
    }
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      child: pw.Text(
        '$label$verif',
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
          color: color,
        ),
      ),
    );
  }

  static pw.Widget _photoCell(DeliveryStop s) {
    final hasPhotos = s.photoPaths.isNotEmpty;
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      child: pw.Text(
        hasPhotos ? 'Yes' : 'No',
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
          color: hasPhotos ? _successGreen : _muted,
        ),
      ),
    );
  }

  static pw.Widget _signatureLine() {
    return pw.Row(
      children: [
        _sigBox('Driver Signature'),
        pw.SizedBox(width: 24),
        _sigBox('Dispatch Manager'),
      ],
    );
  }

  static pw.Widget _sigBox(String label) {
    return pw.Expanded(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            height: 40,
            decoration: pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(color: _rule, width: 0.8),
              ),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(label, style: pw.TextStyle(fontSize: 8, color: _muted)),
        ],
      ),
    );
  }
}
